// Copyright (c) 2026, Salesforce, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Generated Protocol Buffer types for `HyperService`.
//!
//! This module includes the Rust code generated by tonic-build from the
//! `HyperService` protobuf definitions.

/// `HyperService` gRPC types.
#[expect(
    clippy::allow_attributes_without_reason,
    clippy::trivially_copy_pass_by_ref,
    unreachable_pub,
    reason = "generated by tonic-build; wrap with expect rather than hand-editing"
)]
pub(super) mod hyper_service {
    tonic::include_proto!("salesforce.hyperdb.grpc.v1");
}

// Re-export commonly used types for convenience
pub(super) use hyper_service::hyper_service_client::HyperServiceClient;
pub(super) use hyper_service::{
    AttachedDatabase, CancelQueryParam, ExecuteQueryResponse, OutputFormat, QueryInfo,
    QueryInfoParam, QueryParam, QueryResult, QueryResultParam, QueryResultSchema, QueryStatus,
    SqlType,
};
